org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric - https://fabricmc.net/develop
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Версія Minecraft за замовчуванням; усі версії описані в папці versions/
# Збірка під конкретну версію: gradlew build -PmcVersion=1.21.11
mcVersion=26.3

# Mod
mod_version=1.0.0
maven_group=com.w1z4r_d
archives_base_name=noboringarrows
